'use strict';import{AssertionError,AttributeError,BaseException,DeprecationWarning,Exception,IndexError,IterableError,KeyError,NotImplementedError,RuntimeWarning,StopIteration,UserWarning,ValueError,Warning,__JsIterator__,__PyIterator__,__Terminal__,__add__,__and__,__call__,__class__,__envir__,__eq__,__floordiv__,__ge__,__get__,__getcm__,__getitem__,__getslice__,__getsm__,__gt__,__i__,__iadd__,__iand__,__idiv__,__ijsmod__,__ilshift__,__imatmul__,__imod__,__imul__,__in__,__init__,__ior__,__ipow__,
__irshift__,__isub__,__ixor__,__jsUsePyNext__,__jsmod__,__k__,__kwargtrans__,__le__,__lshift__,__lt__,__matmul__,__mergefields__,__mergekwargtrans__,__mod__,__mul__,__ne__,__neg__,__nest__,__or__,__pow__,__pragma__,__proxy__,__pyUseJsNext__,__rshift__,__setitem__,__setproperty__,__setslice__,__sort__,__specialattrib__,__sub__,__super__,__t__,__terminal__,__truediv__,__withblock__,__xor__,abs,all,any,assert,bool,bytearray,bytes,callable,chr,copy,deepcopy,delattr,dict,dir,divmod,enumerate,filter,float,
getattr,hasattr,input,int,isinstance,issubclass,len,list,map,max,min,object,ord,pow,print,property,py_TypeError,py_iter,py_metatype,py_next,py_reversed,py_typeof,range,repr,round,set,setattr,sorted,str,sum,tuple,zip}from"./org.transcrypt.__runtime__.js";var __name__="__main__";delimiter;sum(function(){var __accu0__=[];for(var [i,d]of enumerate(var0.__getslice__(0,null,-1)))__accu0__.append(d*Math.pow(10,i));return py_iter(__accu0__)}());delimiter;export var r=int("".join(map(str,x)));delimiter;datetime.strptime("2010-11-13 10:33:54.227806",
"var0");delimiter;(function(){var __accu0__=[];for(var [i,j]of list(var0.py_items()))__accu0__.append(tuple([i,sum(j)/len(j)]));return __accu0__})();delimiter;zip(var0,var1);delimiter;(function(){var __accu0__=[];for(var i of var1)__accu0__.append("hello{0}".format(i));return __accu0__})();delimiter;re.sub("(?<!\\S)((\\S+)(?:\\s+\\2))(?:\\s+\\2)+(?!\\S)","\\1",var0);delimiter;var0.div(var0.sum(__kwargtrans__({axis:1})),__kwargtrans__({axis:0}));delimiter;map(function __lambda__(t){return tuple([t[1],
t[0]])},var0);delimiter;(function(){var __accu0__=[];for(var t of var0)__accu0__.append(tuple([t[1],t[0]]));return __accu0__})();delimiter;driver.find_element_by_xpath("//p[@id, 'one']/following-sibling::p");delimiter;re.findall('\\[[^\\]]*\\]|\\([^\\)]*\\)|"[^"]*"|\\S+',var1);delimiter;print(list(itertools.combinations(var0,3)));delimiter;var3[["var0","var1","var2"]]=var3.apply(var4,__kwargtrans__({axis:1}));delimiter;soup.find_all("var1",__kwargtrans__({string:"var0"}));delimiter;var0.strftime("var1");
delimiter;int("".join(function(){var __accu0__=[];for(var c of var0)if(c.isdigit())__accu0__.append(c);return py_iter(__accu0__)}()));delimiter;var2["var1"].py_update(dict({"class":dict({"section":5})}));delimiter;dict(function(){var __accu0__=[];for(var x of var0.py_split(","))__accu0__.append(map(int,x.py_split(":")));return py_iter(__accu0__)}());delimiter;driver.find_element_by_xpath("//div[@id='a']//a[@class='click']");delimiter;np.where((var1==tuple([0,1])).all(__kwargtrans__({axis:1})));delimiter;
SomeModel.objects.filter(__kwargtrans__({id:id})).delete();delimiter;dict(var0);delimiter;dict(zip(var0.__getslice__(0,null,2),var0.__getslice__(1,null,2)));delimiter;export var var0=9.8;delimiter;re.findall("(([0-9]+)([A-Z]))","20M10000N80M");delimiter;re.findall("([0-9]+|[A-Z])","var0");delimiter;re.findall("([0-9]+)([A-Z])","var0");delimiter;re.compile("\\w+").findall("var0");delimiter;datetime.datetime.strptime("var0","%H:%M").time();delimiter;requests.py_get("var0",__kwargtrans__({verify:false}));
delimiter;var0[var0!=0];delimiter;export var new_dict=function(){var __accu0__=[];for(var [k,v]of zip(var0,var1))__accu0__.append([k,v]);return dict(__accu0__)}();delimiter;dict(function(){var __accu0__=[];for(var [k,v]of zip(var0,var1))__accu0__.append(tuple([k,v]));return py_iter(__accu0__)}());delimiter;dict(function(){var __accu0__=[];for(var [k,v]of zip(var0,var1))__accu0__.append(tuple([k,v]));return __accu0__}());delimiter;export var m=re.search("\\[(\\w+)\\]",var0);delimiter;var0.setsockopt(SOL_SOCKET,
SO_REUSEADDR,1);delimiter;export var var2=function(){var __accu0__=[];for(var [a,b]of zip(var0,var1))__accu0__.append(a+b);return __accu0__}();delimiter;(function(){var __accu0__=[];for(var c of var0.decode("hex"))__accu0__.append(ord(c));return __accu0__})();delimiter;print(sorted(var0,__kwargtrans__({key:function __lambda__(t){return tuple([-t[2],t[0]])}})));delimiter;(function(){var __accu0__=[];for(var x=0;x<3;x++)for(var y of[x,x])__accu0__.append(y);return __accu0__})();delimiter;export var var1=
open("var0").read();delimiter;var0.__setslice__(0,null,null,function(){var __accu0__=[];for(var x of var0)__accu0__.append(x/var1);return __accu0__}());delimiter;"Name: {0[person.name]}".format(dict({"person.name":"Joe"}));delimiter;var0.py_replace(" ","var1",__kwargtrans__({regex:true}));delimiter;datetime.datetime.combine(var0,datetime.time.min);delimiter;var var1=str(var0);delimiter;time.ctime(os.path.getmtime(var0));delimiter;time.ctime(os.path.getctime(var0));delimiter;export var t=os.path.getmtime(var0);
delimiter;os.var0.getmtime(var0);delimiter;print(__mod__("last modified: %s",time.ctime(os.path.getmtime(var0))));delimiter;print(__mod__("created: %s",time.ctime(os.path.getctime(var0))));delimiter;os.path.getctime(var0);delimiter;(function(){var __accu0__=[];for(var x of re.finditer("[A-Za-z']+",var0))__accu0__.append(x.group(0));return py_iter(__accu0__)})();delimiter;", ".join(["var2"]*len(var0));delimiter;print(re.match("(\\d+(\\.\\d+)?)","var1").group(1));delimiter;var2["var1"].str.py_replace("\\(.*\\)",
"var0");delimiter;var var0=function(){var __accu0__=[];for(var x of var1)if(__in__(x[0],var2))__accu0__.append(x);return __accu0__}();delimiter;print(function(){var __accu0__=[];for(var a of combinations(var0,2))__accu0__.append("".join(a));return __accu0__}());delimiter;(function(){var __accu0__=[];for(var x of var0)if(__in__("var1",x[2]))__accu0__.append(x);return __accu0__})();delimiter;var0.py_sort(__kwargtrans__({key:function __lambda__(x){return x[3]}}));delimiter;logging.info("var0");delimiter;
fig.add_subplot(1,1,1);delimiter;sorted(list(var0.py_items()),__kwargtrans__({key:operator.itemgetter(1)}));delimiter;sorted(var0,__kwargtrans__({key:var0.py_get}));delimiter;sorted(var0,__kwargtrans__({key:var0.py_get,reverse:true}));delimiter;sorted(list(var0.py_items()),__kwargtrans__({key:function __lambda__(x){return x[1]}}));delimiter;np.einsum("ijk,ikl->ijl",var0,var1);delimiter;print("I have: {0.price}".format(var0));delimiter;var1.write("# Data for Class A\n");delimiter;var var0=var0.__getslice__(-1,
null,1)+var0.__getslice__(0,-1,1);delimiter;var0.strftime("var1");delimiter;var0.py_replace("\r\n","\n").py_replace("\r","\n");delimiter;os.path.expanduser("~user");delimiter;export var T=function(){var __accu0__=[];for(var i of var1)__accu0__.append(var0[i]);return __accu0__}();delimiter;var var0=open("var1").read().py_split();delimiter;(function(){var __accu0__=[];for(var i of var0)__accu0__.append([sum(function(){var __accu1__=[];for(var x of i)__accu1__.append(x[1]);return __accu1__}())]);return __accu0__})();
delimiter;(function(){var __accu0__=[];for(var i of data)__accu0__.append(sum(function(){var __accu1__=[];for(var x of i)__accu1__.append(x[1]);return __accu1__}()));return __accu0__})();delimiter;Article.objects.annotate(__kwargtrans__({like_count:Count("var1")})).order_by("-like_count");delimiter;export var today=datetime.datetime.utcnow().date();delimiter;(function(){var __accu0__=[];for(var [a,b]of zip(var0,var1))__accu0__.append(a*b);return __accu0__})();delimiter;re.findall("(?::|;|=)(?:-)?(?:\\)|\\(|D|P)",
var1);delimiter;re.match("var0",var1);delimiter;var var1=json.dumps(function(){var __accu0__=[];for(var ob of var0)__accu0__.append(ob.__dict__);return __accu0__}());delimiter;var var0=[0]*var1;delimiter;var0.decode("utf-8","ignore");delimiter;re.findall("var0","var1");delimiter;var1.py_setdefault(var0,[]).append(var2);delimiter;var0[np.argmin(var0.__getitem__([tuple([0,null,1]),1]))];delimiter;var0.py_update(var1);delimiter;(function(){var __accu0__=[];for(var d of var1)__accu0__.append(function(){var __accu1__=
[];for(var [k,v]of d.py_items())if(k!="var0")__accu1__.append([k,v]);return dict(__accu1__)}());return __accu0__})();delimiter;(function(){var __accu0__=[];for(var d of mylist)__accu0__.append(dict(function(){var __accu1__=[];for(var [k,v]of d.py_items())if(k!="mykey1")__accu1__.append(tuple([k,v]));return py_iter(__accu1__)}()));return __accu0__})();delimiter;numpy.random.random(tuple([3,3]));delimiter;df["var0"]=df["var1"]+df["var2"];delimiter;(function(){var __accu0__=[];for(var [key,value]of list(var0.py_items()))if(__in__("var1",
key.lower()))__accu0__.append(value);return __accu0__})();delimiter;sys.path.append("var0");delimiter;re.findall("\\d+(?=[^[]+$)",var0);delimiter;pickle.load(open("var0","rb"));delimiter;driver.find_element_by_xpath("xpath").click();delimiter;var1.groupby(__kwargtrans__({level:"var0"})).agg(function __lambda__(x){return x.index.get_level_values(1).nunique()});delimiter;pd.concat(map(pd.DataFrame,py_iter(var0.py_values())),__kwargtrans__({py_keys:list(var0.py_keys())})).stack().unstack(0);delimiter;
sum(function(){var __accu0__=[];for(var [i,j]of zip(var0,var1))if(i!=j)__accu0__.append(1);return py_iter(__accu0__)}());delimiter;var var0=function(){var __accu0__=[];for(var [[a,b],v]of list(var0.py_items()))__accu0__.append([tuple([a.lower(),b]),v]);return dict(__accu0__)}();delimiter;var0.py_sort(__kwargtrans__({key:function __lambda__(x){return[x[0],len(x[1]),x[1]]}}));delimiter;var0.strip();delimiter;var var0=var0.lstrip();delimiter;var var0=var0.rstrip();delimiter;var var1=var1.strip(" \t\n\r");
delimiter;print(re.sub("[\\s+]","",var0));delimiter;Task.objects.exclude(__kwargtrans__({prerequisites__status__in:["var1","var2","var3"]}));delimiter;root.configure(__kwargtrans__({background:"black"}));delimiter;numpy.array(function(){var __accu0__=[];for(var [key,val]of var0.py_items())__accu0__.append(tuple([key,val]));return __accu0__}(),dtype);delimiter;pd.concat([var0,var1.sort_values("var2")]);delimiter;re.sub("(.*)</div>","\\1</bad>",var2);delimiter;print(max(d,__kwargtrans__({key:function __lambda__(x){return tuple([d[x]["var0"],
d[x]["var1"]])}})));delimiter;Book.objects.filter(__kwargtrans__({var0__id:var1})).filter(__kwargtrans__({var0__id:var2}));delimiter;re.compile("var1",re.IGNORECASE).py_split("var0");delimiter;(function(){var __accu0__=[];for(var s of var0.py_split())__accu0__.append(sum(map(int,s)));return __accu0__})();delimiter;(function(){var __accu0__=[];for(var i of var0)if(var0[i]==1)__accu0__.append(i);return __accu0__})();delimiter;var0.decode("unicode_escape");delimiter;pd.melt(var2,__kwargtrans__({id_vars:["farm",
"fruit"],var_name:"var0",value_name:"var1"}));delimiter;default_data["var0"]=3;delimiter;default_data.py_update(dict({"var0":3}));delimiter;var2.py_update(dict({"var0":4,"var1":5}));delimiter;var0.__getslice__(0,3,1)+var0.__getslice__(-3,null,1);delimiter;var var0=var0.reset_index(__kwargtrans__({drop:true}));delimiter;(function(){var __accu0__=[];for(var var0=0;var0<3;var0++)__accu0__.append(a[var0].append(var1[var0]));return __accu0__})();delimiter;os.var0.realpath(var0);delimiter;set(var0).issubset(set(var1));
delimiter;zip(...np.where(a==1));delimiter;np.where(a==1);delimiter;var0.columns=var0.columns.get_level_values(0);delimiter;export var x=scipy.matrix(var0).transpose();delimiter;var var2=re.sub("(\\bget\\b)","\\1@",var2);delimiter;np.array([np.arange(3),np.arange(2,-1,-1),np.ones(tuple([3]))]).min(__kwargtrans__({axis:0}));delimiter;var1["var0"]=list(range(1,len(var1)+1));delimiter;os.environ["var0"]="1";delimiter;print(os.environ["var0"]);delimiter;os.environ["var0"]="var1";delimiter;var0.py_update(var1);
delimiter;var1["var0"];delimiter;var var0=plt.errorbar(x,var2,__kwargtrans__({yerr:err,ecolor:"var2"}));delimiter;results+=function(){var __accu0__=[];for(var each of os.listdir(var1))if(each.endswith("var0"))__accu0__.append(each);return __accu0__}();delimiter;re.sub("var0","-\\1",var1).lower();delimiter;os.system("ulimit -s unlimited; some_executable");delimiter;"{0:.3g}".format(var0);delimiter;numpy.append(var0,var0[0]);delimiter;var0.ix.__getitem__([tuple([0,null,1]),var0.loc[0]==38.15]).columns;
delimiter;var1["var2"]=var1.CET.map(var0.set_index("var3")["var2"]);delimiter;var var1=json.loads(var0);delimiter;math.cos(math.radians(1));delimiter;sum(function(){var __accu0__=[];for(var x of var0)__accu0__.append(isinstance(x,int));return py_iter(__accu0__)}());delimiter;"used<200b>".py_replace("\u200b","var1");delimiter;threading.Thread(__kwargtrans__({target:var0})).start();delimiter;sum(function(){var __accu0__=[];for(var i of var0)__accu0__.append(i*i);return py_iter(__accu0__)}());delimiter;
sum(map(function __lambda__(x){return x*x},var0));delimiter;var var0=dict(function(){var __accu0__=[];for(var [key,value]of var1)__accu0__.append(tuple([key,value]));return py_iter(__accu0__)}());delimiter;var var0=function(){var __accu0__=[];for(var [key,value]of var1)__accu0__.append([key,value]);return dict(__accu0__)}();delimiter;var var0=function(){var __accu0__=[];for(var [k,v]of var1)__accu0__.append([k,v]);return dict(__accu0__)}();delimiter;var0.round(dict({"var1":2,"var2":3}));delimiter;
var1.setopt(pycurl.var0,function __lambda__(x){return null});delimiter;print(random.choice(var0));delimiter;max(var1,__kwargtrans__({key:function __lambda__(x){return var1[x]["var0"]}}));delimiter;(function(){var __accu0__=[];for(var x of var0.py_split(","))__accu0__.append(x?int(x):0);return __accu0__})();delimiter;"var1".join(function(){var __accu0__=[];for(var x of var0.py_split("var1"))__accu0__.append(x||"0");return py_iter(__accu0__)}());delimiter;re.compile("$^");delimiter;re.compile(".\\A|.\\A*|.\\A+");
delimiter;re.compile("a^");delimiter;var0.columns[var0.max()>0];delimiter;var0.date()==datetime.today().date();delimiter;print("\u001b[1m"+"var0");delimiter;re.sub(".{20}(.mkv)","\\1","var1");delimiter;var0;delimiter;" ".join(var0.py_split());delimiter;print("{:.100f}".format(2.345E-67));delimiter;if(__in__("var0",var1));delimiter;if(__in__(var0,var1));delimiter;Blog.objects.filter(__kwargtrans__({pk__in:[var0]}));delimiter;export var f=open("var0","rb");delimiter;format(1.234567846E7,"var2").py_replace("var2",
"var0").py_replace("var1","var2");delimiter;pd.merge(var0,var1,__kwargtrans__({left_on:"var2",right_on:"var3"}));delimiter;np.isnan(var0).sum()/np.prod(var0.shape);delimiter;sorted(py_iter(var0.py_items()),__kwargtrans__({key:function __lambda__(k_v){return k_v[1][2]},reverse:true}));delimiter;sorted(list(var0.py_items()),__kwargtrans__({key:function __lambda__(v){return v[1]}}));delimiter;sorted(list(var0.py_items()),__kwargtrans__({key:function __lambda__(k_v){return k_v[1]},reverse:true}));delimiter;
sorted(list(var0.py_items()),__kwargtrans__({key:function __lambda__(k_v){return k_v[1]}}));delimiter;var f=open(os.path.join(__location__,"var0"));delimiter;var f=open("var0","var1");delimiter;(function(){var __accu0__=[];for(var k of var1)__accu0__.append([k,float(var1[k])/var0[k]]);return dict(__accu0__)})();delimiter;(function(){var __accu0__=[];for(var var0 of list(var2.py_keys())&var1)__accu0__.append([var0,var1[var0]/var2[var0]]);return dict(__accu0__)})();delimiter;dict(function(){var __accu0__=
[];for(var k of var1)__accu0__.append(tuple([k,float(var1[k])/var0[k]]));return py_iter(__accu0__)}());delimiter;var0.to_csv(var1,__kwargtrans__({date_format:"var2"}));delimiter;var1.py_pop("var0",null);delimiter;export var b=np.where(np.isnan(var0),0,var0);delimiter;subprocess.call("var0",__kwargtrans__({shell:true}));delimiter;subprocess.call("var0",__kwargtrans__({shell:true}));delimiter;var var0=urllib.request.urlopen(url,urllib.parse.unquote(urllib.parse.urlencode(params)));delimiter;"var0".rstrip();
delimiter;urllib.parse.quote(var0.encode("utf-8"));delimiter;urllib.parse.quote_plus("a b");delimiter;np.array(map(int,"var0"));delimiter;print(np.array(list(var0),__kwargtrans__({dtype:int})));delimiter;var var1=cv2.imread("var0",0);delimiter;var0.py_sort(__kwargtrans__({key:function __lambda__(x){return x[2]},reverse:true}));delimiter;export var indices=function(){var __accu0__=[];for(var [i,x]of enumerate(my_list))if(x=="whatever")__accu0__.append(i);return __accu0__}();delimiter;subprocess.call("var0",
__kwargtrans__({shell:true}));delimiter;len(var0)-len(var0.rstrip("?"));delimiter;var1[var1.columns.__getslice__(1,null,1)].py_replace("[\\$,]","",__kwargtrans__({regex:true})).astype(float);delimiter;var2.merge(var1,__kwargtrans__({how:"left",on:"var0"}));delimiter;print(__mod__(len(var0),2)?"".join(function(){var __accu0__=[];for(var i of zip(a2,a1))__accu0__.append("".join(i));return py_iter(__accu0__)}())+var0[-1]:"");delimiter;var0.attributes("-topmost",true);delimiter;var0.lift();delimiter;
hex(int("".join(function(){var __accu0__=[];for(var b of var0)__accu0__.append(str(int(b)));return __accu0__}()),2));delimiter;hex(sum(function(){var __accu0__=[];for(var [i,b]of enumerate(py_reversed(var0)))__accu0__.append(b<<i);return py_iter(__accu0__)}()));delimiter;print(tuple(["var0",var1,"var2",var3]));delimiter;print("Total score for {} is {}".format(var0,var1));delimiter;print(__mod__("Total score for %s is %s  ",tuple([var0,var1])));delimiter;print(tuple(["Total score for",var0,"is",var1]));
delimiter;url("^$",TemplateView.as_view(__kwargtrans__({template_name:"var0"})));delimiter;var1[var1["A"].isin([3,6])];delimiter;instance.__class__.__name__;delimiter;system("var1/bin/python var0");delimiter;var1.objects.values_list("var0",__kwargtrans__({flat:true}));delimiter;re.findall("\\d|\\d,\\d\\)","var0");delimiter;input("var0");delimiter;"^Avar0".encode("hex");delimiter;db.Doc.py_update(dict({"_id":var1["_id"]}),dict({"$set":dict({"var0":myGeolocCountry})}));delimiter;re.sub("l+","l","var0lll");
delimiter;export var rows=var1.findAll("var0").__getslice__(4,null,5);delimiter;plt.gca().invert_xaxis();delimiter;plt.gca().invert_yaxis();delimiter;pd.concat([GOOG,AAPL],__kwargtrans__({py_keys:["GOOG","AAPL"],axis:1}));delimiter;HttpResponse(json.dumps(var0),__kwargtrans__({content_type:"application/json"}));delimiter;var0.decode("string_escape");delimiter;hashlib.md5(open("var0","rb").read()).hexdigest();delimiter;(function(){var __accu0__=[];for(var [k,v]of var0.py_items())if(v==var1)__accu0__.append(k);
return __accu0__})();delimiter;(function(){var __accu0__=[];for(var d of var0)for(var k of list(d.py_keys()))__accu0__.append(k);return set(__accu0__)})();delimiter;set(function(){var __accu0__=[];for(var s of function(){var __accu1__=[];for(var d of var0)__accu1__.append(list(d.py_keys()));return __accu1__}())for(var i of s)__accu0__.append(i);return __accu0__}());delimiter;(function(){var __accu0__=[];for(var s of function(){var __accu1__=[];for(var d of var0)__accu1__.append(list(d.py_keys()));
return __accu1__}())for(var i of s)__accu0__.append(i);return __accu0__})();delimiter;var __left0__=zip(...list(var0.py_items()));export var py_keys=__left0__[0];export var py_values=__left0__[1];delimiter;int(Decimal(var0));delimiter;int(s.py_split(".")[0]);delimiter;numpy.in1d(var0,var1).all();delimiter;numpy.array(function(){var __accu0__=[];for(var x of var1)__accu0__.append(__in__(x,var0));return __accu0__}());delimiter;networkx.draw_networkx_labels(G,var2,var0);delimiter;var var0=function(){var __accu0__=
[];for(var row of var1)__accu0__.append(row.__getslice__(0,null,1));return __accu0__}();delimiter;export var X=numpy.loadtxt("var0",__kwargtrans__({delimiter:","}));delimiter;export var matching=function(){var __accu0__=[];for(var s of var0)if(__in__("var1",s))__accu0__.append(s);return __accu0__}();delimiter;var0.to_csv("var1",__kwargtrans__({sep:"\t"}));delimiter;random.sample(list(range(100)),10);delimiter;var0.rsplit(",",1);delimiter;all(function(){var __accu0__=[];for(var x of var0)__accu0__.append(isinstance(x,
int));return py_iter(__accu0__)}());delimiter;all(function(){var __accu0__=[];for(var x of var0)__accu0__.append(isinstance(x,var1));return py_iter(__accu0__)}());delimiter;var0.strip();delimiter;driver.execute_script("window.scrollTo(0, Y)");delimiter;driver.execute_script("window.scrollTo(0, document.body.scrollHeight);");delimiter;datetime.datetime.combine(var0,datetime.time());delimiter;print(any(function(){var __accu0__=[];for(var x of var0)__accu0__.append(__in__(x,var1));return py_iter(__accu0__)}()));
delimiter;scipy.misc.imsave("var1",var0);delimiter;var var0=re.sub(" ?\\([^)]+\\)","",var0);delimiter;var var0=re.sub(" ?\\(\\w+\\)","",var0);delimiter;var var0=re.sub(" \\(\\w+\\)","",var0);delimiter;len(set(var0).intersection(var1))>0;delimiter;export var i=int(var0,16);delimiter;int("var0",16);delimiter;int("var0",16);delimiter;ast.literal_eval("var0");delimiter;int("var0",16);delimiter;os.system("screencapture var0");delimiter;driver.set_window_size(var0);delimiter;pandas.concat([var0,var1]).drop_duplicates().reset_index(__kwargtrans__({drop:true}));
delimiter;var var0=numpy.fromfile("var1",__kwargtrans__({dtype:numpy.float32}));delimiter;subprocess.call("var0",__kwargtrans__({shell:true}));delimiter;subprocess.call("mv /home/somedir/subdir/* somedir/",__kwargtrans__({shell:true}));delimiter;difflib.SequenceMatcher(null,var0.read(),var1.read());delimiter;dict(function(){var __accu0__=[];for(var [k,v]of function(){var __accu1__=[];for(var var0 of s.py_split("var2"))__accu1__.append(var0.py_split(" - "));return py_iter(__accu1__)}())__accu0__.append(tuple([k,
int(v)]));return py_iter(__accu0__)}());delimiter;all(function(){var __accu0__=[];for(var i of var0)__accu0__.append(__in__(i,var1));return py_iter(__accu0__)}());delimiter;var1["var0"].map(function __lambda__(t){return t.date()}).unique();delimiter;"{:>7s}".format(var0);delimiter;open("var0","rb").read(200);delimiter;var0.sort_values(["var1","var2"],__kwargtrans__({ascending:[true,false],inplace:true}));delimiter;var0.sort_values(["var1","var2"],__kwargtrans__({ascending:[true,false]}));delimiter;
df1.py_sort(["var0","var1"],__kwargtrans__({ascending:[true,false],inplace:true}));delimiter;df.py_sort(["var0","var1"],__kwargtrans__({ascending:[true,false]}));delimiter;redirect("var0");delimiter;(function(){var __accu0__=[];for(var x of var1)if(!__in__(x,[2,3,7]))__accu0__.append(x);return __accu0__})();delimiter;export var out="".join(function(){var __accu0__=[];for(var c of var3)if(!__in__(c,tuple(["var0","var1","var2"])))__accu0__.append(c);return py_iter(__accu0__)}());delimiter;var4.find("var3",
dict({"var1":"var2"}))["var0"];delimiter;urllib.parse.unquote("var0");delimiter;urllib.parse.unquote(var0).decode("utf8");delimiter;deletevar0.__getslice__(0,null,1);delimiter;deletevar01.__getslice__(0,null,1);delimiter;var0.__setslice__(0,null,null,[]);delimiter;var0.__setslice__(0,null,null,[]);delimiter;var0.reset_index(0).reset_index(__kwargtrans__({drop:true}));delimiter;var0[0].getText().encode("var1");delimiter;(function(){var __accu0__=[];for(var [x,y]of zip(var0,var0.__getslice__(1,null,
1)))__accu0__.append(y-x);return __accu0__})();delimiter;print(re.search("\\bLOG_ADDR\\s+(\\S+)",var0).group(1));delimiter;__all__.py_update(importlib.import_module("var0").__dict__);delimiter;"".join(var0);delimiter;var0.py_split("var1");delimiter;export var od=collections.OrderedDict(sorted(var0.py_items()));delimiter;OrderedDict(sorted(list(var0.py_items()),__kwargtrans__({key:function __lambda__(t){return t[0]}})));delimiter;export var response=requests.put(var0,__kwargtrans__({data:json.dumps(data),
headers:headers}));delimiter;re.sub("[\\W_]+","var0",var1);delimiter;(function(){var __accu0__=[];for(var x of var0)for(var y of var1)__accu0__.append(x+y);return __accu0__})();delimiter;dict(function(){var __accu0__=[];for(var x of s.py_split())__accu0__.append(x.py_split("="));return __accu0__}());delimiter;var0.py_pop(2);delimiter;var var1=var1.py_replace("var0","");delimiter;export var newstr=oldstr.py_replace("M","");delimiter;sum(function(){var __accu0__=[];for(var [x,y]of zip(var0,var1))__accu0__.append(x*
y);return py_iter(__accu0__)}());delimiter;list(function(){var __accu0__=[];for(var [x,y]of list(zip(var0,var1)))__accu0__.append(x*y);return py_iter(__accu0__)}());delimiter;sum(function(){var __accu0__=[];for(var [i,j]of zip(var0,var1))__accu0__.append(i*j);return py_iter(__accu0__)}());delimiter;sum(function(){var __accu0__=[];for(var [x,y]of list(zip(var0,var1)))__accu0__.append(x*y);return py_iter(__accu0__)}());delimiter;var1.write(open("var0","rb").read());delimiter;export var new_list=function(){var __accu0__=
[];for(var x of var0)__accu0__.append(x+1);return __accu0__}();delimiter;(function(){var __accu0__=[];for(var x of var0)if(x>=5)__accu0__.append(x);return __accu0__})();delimiter;plt.plot(list(range(10)),"var0");delimiter;plt.plot(list(range(10)),__kwargtrans__({linestyle:"--",marker:"o",color:"b"}));delimiter;(function(){var __accu0__=[];for(var i of var0)__accu0__.append(i.py_split("\t",1)[0]);return __accu0__})();delimiter;var var0=function(){var __accu0__=[];for(var i of var0)__accu0__.append(i.py_split("\t")[0]);
return __accu0__}();delimiter;sum(var0);delimiter;var0().set_trace();delimiter;export var result=function(){var __accu0__=[];for(var [k,v]of list(var0.py_items()))__accu0__.append([k,var1.py_get(v)]);return dict(__accu0__)}();delimiter;datetime.datetime.now()+datetime.timedelta(__kwargtrans__({days:1,hours:3}));delimiter;(function(){var __accu0__=[];for(var i=0;i<len(s);i+=3)__accu0__.append(int(s.__getslice__(i,i+3,1),2));return __accu0__})();delimiter;dict(function(){var __accu0__=[];for(var [k,
v]of var0.py_items())__accu0__.append(tuple([v,k]));return py_iter(__accu0__)}());delimiter;print(sorted(var0,__kwargtrans__({key:function __lambda__(x){return int(x.py_split("var1")[2])}})));delimiter;any(function(){var __accu0__=[];for(var d of var2)__accu0__.append(d["var0"]=="var1");return py_iter(__accu0__)}());delimiter;var0.__setslice__(0,null,null,function(){var __accu0__=[];for(var x of var0)if(x!=[1,1])__accu0__.append(x);return __accu0__}());delimiter;(function(){var __accu0__=[];for(var x of var1)if(x!=
[1,1])__accu0__.append(x);return __accu0__})();delimiter;var b=function(){var __accu0__=[];for(var i=0;i<len(var0);i+=2)__accu0__.append([var0[i],var0[i+1]]);return dict(__accu0__)}();delimiter;len(set(var0))==len(var0);delimiter;print(hashlib.md5(open(var0,"rb").read()).hexdigest());delimiter;sorted(list(data.py_items()),__kwargtrans__({key:function __lambda__(x){return x[1][0]}}));delimiter;"".join(function(){var __accu0__=[];for(var x of var0)__accu0__.append(random.randint(0,1)?x.upper():x);return py_iter(__accu0__)}());
delimiter;os.system('GREPDB="echo 123"; var0 -c "$GREPDB"');delimiter;os.system('/bin/bash -c "var0"');delimiter;getattr(var1,var0);delimiter;Image.open("var0").show();delimiter;"var0".py_replace("'","var1");delimiter;var0.py_sort(__kwargtrans__({key:var1}));delimiter;var0.py_replace(" ","");delimiter;var0.strip();delimiter;var var0=re.sub("\\s+","",var0,__kwargtrans__({flags:re.UNICODE}));delimiter;var var0="".join(var0.py_split());delimiter;sum(var0.py_values());delimiter;np.sqrt(Math.pow(var0-
var1,2).sum(-1));delimiter;var var0=[dict({}),dict({}),dict({})];delimiter;export var weekly=function(){var __accu0__=[];for(var x=0;x<len(var0);x+=7)__accu0__.append(sum(visitors.__getslice__(x,x+7,1)));return __accu0__}();delimiter;deletevar1[var0];delimiter;(function(){var __accu0__=[];for(var i of var0)if(i!=0)__accu0__.append([i,var0[i]]);return dict(__accu0__)})();delimiter;var1.py_pop("var0");delimiter;deletevar1[var0];delimiter;np.linalg.solve(np.dot(var0.T,var0),np.dot(var0.T,var1));delimiter;
pd.concat([var1.drop("var0",__kwargtrans__({axis:1})),pd.DataFrame(var1["var0"].tolist())],__kwargtrans__({axis:1}));delimiter;for(var i=0;i<10;i+=2);delimiter;for(var i of var0.__getslice__(0,null,2));delimiter;(function(){var __accu0__=[];for(var x of var1)__accu0__.append(dict({"var0":x["var0"].lower()}));return __accu0__})();delimiter;" ".join(var0);delimiter;re.sub("(http://\\S+|\\S*[^\\w\\s]\\S*)","var2",var1);delimiter;var0(n)==var0(n).__getslice__(0,null,-1);delimiter;ftp.storbinary("STOR myfile.txt",
open("var0","rb"));delimiter;re.sub(".*I","var1",var0);delimiter;int("var0".py_replace(",",""));delimiter;pd.merge(var0,var1,__kwargtrans__({left_index:true,right_index:true,how:"outer"}));delimiter;pandas.concat([df1,df2],__kwargtrans__({axis:1}));delimiter;all(var0.py_values());delimiter;var2.var1.str.py_replace("var0","");delimiter;var0.__getslice__(0,null,-1);delimiter;py_reversed(var0);delimiter;var0.reverse();delimiter;list(py_reversed(var0));delimiter;(function(){var __accu0__=[];for(var tup of var0)__accu0__.append(tup[0]);
return __accu0__})();delimiter;export var newcontents=var4.py_replace("var0","var1").py_replace("var2","var3");delimiter;json.dumps(function(){var __accu0__=[];for(var var0 of rs)__accu0__.append(dict(list(var0.py_items())));return __accu0__}());delimiter;export var config_file=os.path.expanduser("var0");delimiter;request.params.getall("c");delimiter;np.corrcoef(var0);delimiter;print(maxvar0);delimiter;self.request.py_get("var0");delimiter;var1["var0"].apply(function __lambda__(var0,y){return var0+
y},__kwargtrans__({args:tuple([100])}));delimiter;var0.objects.order_by("-pet__age").__getslice__(0,10,1);delimiter;time.sleep(var0);delimiter;time.sleep(60);delimiter;sleep(.1);delimiter;time.sleep(60);delimiter;time.sleep(.1);delimiter;(function(){var __accu0__=[];for(var x of var0)if(!any(function(){var __accu1__=[];for(var c of x)__accu1__.append(c.isdigit());return py_iter(__accu1__)}()))__accu0__.append(x);return __accu0__})();delimiter;var1["var0"].apply(function __lambda__(x){return x.__getslice__(len(x)/
2-1,len(x)/2+1,1)});delimiter;var0.grid(true);

//# sourceMappingURL=P2JSnippets.map